spellcheck + install scripts + copy bash files

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -2,7 +2,7 @@
 # This script installs all packages and configfiles, removes old config filesset
 
 # Constants
-SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
+SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 # Variables
 unalias cp
 # Functions
@@ -29,9 +29,9 @@ install_packages(){
     while read line
     do
         packages=$packages' '$line
-    done < $filepath
+    done < "$filepath"
     echo -e "\e[34mInstalling: $packages\e[0m"
-    sudo apt-get install -y $packages
+    sudo apt-get install -y "$packages"
     # FLATPAK
     echo -e "\e[34mFLATPAK\e[0m"
     flatpak update
@@ -40,9 +40,9 @@ install_packages(){
     while read line
     do
         packages=$packages' '$line
-    done < $filepath
+    done < "$filepath"
     echo -e "\e[34mInstalling: $packages\e[0m"
-    flatpak install -y $packages
+    flatpak install -y "$packages"
     # SNAP
     echo -e "\e[34mSNAP\e[0m"
     sudo snap refresh
@@ -51,25 +51,25 @@ install_packages(){
     while read line
     do
         packages=$packages' '$line
-    done < $filepath
+    done < "$filepath"
     echo -e "\e[34mInstalling: $packages\e[0m"
-    sudo snap install $packages
+    sudo snap install "$packages"
 }
 
 install_configs(){
     # Gnome Terminal Dracula Theme
     echo -e "\e[34mSetting Gnome Terminal...\e[0m"
     git clone https://github.com/dracula/gnome-terminal
-    cd gnome-terminal
+    cd gnome-terminal || exit
     ./install.sh
     cd ../
     rm -rf gnome-terminal
     
-    eval `dircolors /home/$USER/.dir_colors/dircolors`
+    eval "$(dircolors "/home/$USER/.dir_colors/dircolors")"
     
     # Neovim
-    echo -e "\e[34mSetting Neovim...\e[0m"
-    echo 'alias v=nvim' >> /home/$USER/.bashrc # alias for nvim
+    # echo -e "\e[34mSetting Neovim...\e[0m"
+    # echo 'alias v=nvim' >> /home/$USER/.bashrc # alias for nvim
     
     # OneDrive
     echo -e "\e[34mSetting OneDrive...\e[0m"
@@ -99,46 +99,60 @@ install_configs(){
     sleep 2
     onedrive
     # Copy the personal account config files
-    cp -r $SCRIPT_DIR"/../configs/onedrive/onedrive/config" /home/$USER/.config/onedrive
+    cp -r "$SCRIPT_DIR""/../configs/onedrive/onedrive/config" /home/"$USER"/.config/onedrive
     
     # TODO add a check if there already is a folder, if so, notify that it will be overwritten
-    mkdir $choice
+    mkdir "$choice"
     # Replace the default save-location with the one specified
-    mkdir $choice'/Private/'
-    cd /home/$USER/.config/onedrive
+    mkdir "$choice"'/Private/'
+    cd /home/"$USER"/.config/onedrive || exit
     
     # https://stackoverflow.com/questions/11145270/how-to-replace-an-entire-line-in-a-text-file-by-line-number
-    sed -i '7s#.*#sync_dir = "'$choice'/Private/"#' config
+    sed -i '7s#.*#sync_dir = "'"$choice"'/Private/"#' config
     
     # Make onedrive school setup
-    cp -r $SCRIPT_DIR"/../configs/onedrive/onedrive-school" /home/$USER/.config/
+    cp -r "$SCRIPT_DIR""/../configs/onedrive/onedrive-school" /home/"$USER"/.config/
     
     # Replace the default save-location with the one specified
-    mkdir $choice'/School/'
-    cd /home/$USER/.config/onedrive-school
+    mkdir "$choice"'/School/'
+    cd /home/"$USER"/.config/onedrive-school || exit
     
     # https://stackoverflow.com/questions/11145270/how-to-replace-an-entire-line-in-a-text-file-by-line-number
-    sed -i '7s#.*#sync_dir = "'$choice'/School/"#' config
+    sed -i '7s#.*#sync_dir = "'"$choice"'/School/"#' config
     
     echo -e "\e[34mPlease authenticate with your school account.\e[0m"
     sleep 2
     onedrive --confdir="~/.config/onedrive-school"
     
     # Setup notification daemon for OneDrive Private
-    sudo systemctl stop onedrive@$USER.service
-    sudo systemctl disable onedrive@$USER.service
+    sudo systemctl stop onedrive@"$USER".service
+    sudo systemctl disable onedrive@"$USER".service
     
     systemctl --user enable onedrive
     systemctl --user start onedrive
     
     # Setup notification daemon for OneDrive School
-    cd /usr/lib/systemd/user/
+    cd /usr/lib/systemd/user/ || exit
     sudo cp onedrive.service onedrive-school.service
     
-    sed -i '8s#.*#ExecStart=/usr/bin/onedrive --monitor --confdir="/home/'$USER'/.config/onedrive-school#' onedrive-school.service
+    sed -i '8s#.*#ExecStart=/usr/bin/onedrive --monitor --confdir="/home/'"$USER"'/.config/onedrive-school#' onedrive-school.service
     
     systemctl --user enable onedrive-school
     systemctl --user start onedrive-school
+    
+    # Install scripts
+    cd "$SCRIPT_DIR" || exit
+    git clone https://github.com/quiode/scripts
+    cd scripts || exit
+    sudo cp -r onedrive/onedrive-status /opt && chmod +x /opt/onedrive-status # Install onedrive-status script
+    
+    sudo rm -r "$SCRIPT_DIR"/scripts # clean up
+    
+    # copy bash files
+    cp -r "$SCRIPT_DIR""/../configs/bash/." /home/"$USER"/
+    
+    # NVM
+    # TODO: implement
 }
 
 
